config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about", as: "homes_about"
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :info, :warning, :danger

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      redirect_to book_path(@book), success: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book), success: "You have updated book successfully."
    else
    render'edit'
    end
  end

  private

  def book_params
   params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_edit_check_action, only:[:edit]

  def index
    @user = User.all
    @book_new = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), success: "You have updated user successfully."
    else
    render'edit'
    end
  end


  private

  def user_edit_check_action
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <div class="col-md-3">
    <h2>User info</h2>
    <table class="table">
      <tbody>
        <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpeg", fallback:"no_image.jpeg" %></tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>

    <h2 class="mt-3">New book</h2>
    <div class="form-group">
      <%= form_with model: book_new, url: books_path, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <div class="actions">
          <%= f.submit "Create Book", class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %></ul>
  <% end %>
  <%= form_with model: @book, url: book_path, local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <div class="actions">
    <%= f.submit "Update Book", class:"btn btn-success" %>
    </div>
  <% end %>
  <%= link_to "Show",book_path(@book) %>|<%= link_to "Back",books_path %>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %></ul>
  <% end %>
  <div class="row">

    <%= render 'books/list', user: @user, book_new: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback:"no_image.jpeg", size:'40x40' %></td>
                <% end %>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% flash.each do |key, value| %>
  <%= value %>
<% end %>
<br>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'books/list', user: @book.user, book_new: @book_new %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
            <tr>
                <td>
                 <%= link_to user_path(@book.user) do %>
                     <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback:"no_image.jpeg", size:'40x40' %>
                     <br><%= @book.user.name %><br/>
                 <% end %>
                </td>
              <td>
                <%= link_to book_path(@book) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success' %></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-sm btn-danger' %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<% flash.each do |key, value| %>
  <%= value %>
<% end %>
<br>
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= "Bookers" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home">Home</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users">Users</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open">Books</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, success: "Signed out successfully.", class: 'nav-link text-light', method: :delete do %>
                <i class="fas fa-sign-out-alt">logout</i>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home">Home</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to homes_about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link">About</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus">sign up</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt">login</i>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
      	  <div class="mx-auto">
      		  <p>CopyRight Infratop.inc</p>
      	  </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpeg", fallback:"no_image.jpeg" %></tr>
          <tr>
    	      <th>name</th>
    	      <th><%= user.name %></th>
          </tr>
          <tr>
    	      <th>introduction</th>
    	      <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
      <div class="form-group">
        <%= form_with model: book_new, url: books_path, local:true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <div class="actions">
          <%= f.submit "Create Book", class:"btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
      <%= @user.errors.count %>errors prohibited this book from being saved:
      <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %></ul>
      <% end %>
      <%= form_with model:@user, local: true do |f| %>
        <label>Name</label><br />
        <%= f.text_field :name %><br />
        <label>Image</label><br />
        <%= f.attachment_field :profile_image %><br />
        <label>Introduction</label><br />
        <%= f.text_area :introduction %><br />
        <%= f.submit 'Update User' %>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/list', user: current_user, book_new: @book_new %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback:"no_image.jpeg", size:'40x40' %></td>
              <td><%= user.name %></td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% flash.each do |key, value| %>
  <%= value %>
<% end %>
<br>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/list', user: @user, book_new: @book_new %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
              <% @books.each do |book| %>
              <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback:"no_image.jpeg", size:'40x40' %></td>
                <% end %>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>